name: data
on:
  push:
    branches:
      - main
  schedule:
    cron: "* * * * *"
jobs:
  Vaccination Data:
    runs_on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@main
        with:
          outfile_basename: ""
          http_url: https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data
