name: data
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch: {}
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v1
        with:
          http_url: https://api.vaccinateca.com/v1/locations.json
          outfile_basename: data
          postprocess: ./postprocessor.js
      - name: Fetch data
        uses: githubocto/flat@v1
        with:
          http_url: https://api.vaccinateca.com/v1/locations.json
          outfile_basename: post_process_data
      - name: Fetch data
        uses: githubocto/flat@v1
        with:
          sql_connstring: ${{ secrets.FLAT_32QY32_CONNSTRING }}
          sql_queryfile: ./query.sql
          sql_format: csv
          outfile_basename: results
